/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface OracleSlippageTestInterface extends utils.Interface {
  functions: {
    "WETH9()": FunctionFragment;
    "checkOracleSlippage(bytes[],uint128[],uint24,uint32)": FunctionFragment;
    "checkOracleSlippage(bytes,uint24,uint32)": FunctionFragment;
    "factory()": FunctionFragment;
    "registerPool(address,address,address,uint24)": FunctionFragment;
    "setTime(uint256)": FunctionFragment;
    "testGetBlockStartingAndCurrentTick(address)": FunctionFragment;
    "testGetSyntheticTicks(bytes[],uint128[],uint32)": FunctionFragment;
    "testGetSyntheticTicks(bytes,uint32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "WETH9"
      | "checkOracleSlippage(bytes[],uint128[],uint24,uint32)"
      | "checkOracleSlippage(bytes,uint24,uint32)"
      | "factory"
      | "registerPool"
      | "setTime"
      | "testGetBlockStartingAndCurrentTick"
      | "testGetSyntheticTicks(bytes[],uint128[],uint32)"
      | "testGetSyntheticTicks(bytes,uint32)"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "WETH9", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "checkOracleSlippage(bytes[],uint128[],uint24,uint32)",
    values: [
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "checkOracleSlippage(bytes,uint24,uint32)",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerPool",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setTime",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "testGetBlockStartingAndCurrentTick",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "testGetSyntheticTicks(bytes[],uint128[],uint32)",
    values: [
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "testGetSyntheticTicks(bytes,uint32)",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "WETH9", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkOracleSlippage(bytes[],uint128[],uint24,uint32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkOracleSlippage(bytes,uint24,uint32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setTime", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "testGetBlockStartingAndCurrentTick",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testGetSyntheticTicks(bytes[],uint128[],uint32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testGetSyntheticTicks(bytes,uint32)",
    data: BytesLike
  ): Result;

  events: {};
}

export interface OracleSlippageTest extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: OracleSlippageTestInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    WETH9(overrides?: CallOverrides): Promise<[string]>;

    "checkOracleSlippage(bytes[],uint128[],uint24,uint32)"(
      paths: PromiseOrValue<BytesLike>[],
      amounts: PromiseOrValue<BigNumberish>[],
      maximumTickDivergence: PromiseOrValue<BigNumberish>,
      secondsAgo: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "checkOracleSlippage(bytes,uint24,uint32)"(
      path: PromiseOrValue<BytesLike>,
      maximumTickDivergence: PromiseOrValue<BigNumberish>,
      secondsAgo: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    factory(overrides?: CallOverrides): Promise<[string]>;

    registerPool(
      pool: PromiseOrValue<string>,
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setTime(
      _time: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    testGetBlockStartingAndCurrentTick(
      pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [number, number] & { blockStartingTick: number; currentTick: number }
    >;

    "testGetSyntheticTicks(bytes[],uint128[],uint32)"(
      paths: PromiseOrValue<BytesLike>[],
      amounts: PromiseOrValue<BigNumberish>[],
      secondsAgo: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        averageSyntheticAverageTick: BigNumber;
        averageSyntheticCurrentTick: BigNumber;
      }
    >;

    "testGetSyntheticTicks(bytes,uint32)"(
      path: PromiseOrValue<BytesLike>,
      secondsAgo: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        syntheticAverageTick: BigNumber;
        syntheticCurrentTick: BigNumber;
      }
    >;
  };

  WETH9(overrides?: CallOverrides): Promise<string>;

  "checkOracleSlippage(bytes[],uint128[],uint24,uint32)"(
    paths: PromiseOrValue<BytesLike>[],
    amounts: PromiseOrValue<BigNumberish>[],
    maximumTickDivergence: PromiseOrValue<BigNumberish>,
    secondsAgo: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<void>;

  "checkOracleSlippage(bytes,uint24,uint32)"(
    path: PromiseOrValue<BytesLike>,
    maximumTickDivergence: PromiseOrValue<BigNumberish>,
    secondsAgo: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<void>;

  factory(overrides?: CallOverrides): Promise<string>;

  registerPool(
    pool: PromiseOrValue<string>,
    tokenIn: PromiseOrValue<string>,
    tokenOut: PromiseOrValue<string>,
    fee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setTime(
    _time: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  testGetBlockStartingAndCurrentTick(
    pool: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [number, number] & { blockStartingTick: number; currentTick: number }
  >;

  "testGetSyntheticTicks(bytes[],uint128[],uint32)"(
    paths: PromiseOrValue<BytesLike>[],
    amounts: PromiseOrValue<BigNumberish>[],
    secondsAgo: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      averageSyntheticAverageTick: BigNumber;
      averageSyntheticCurrentTick: BigNumber;
    }
  >;

  "testGetSyntheticTicks(bytes,uint32)"(
    path: PromiseOrValue<BytesLike>,
    secondsAgo: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      syntheticAverageTick: BigNumber;
      syntheticCurrentTick: BigNumber;
    }
  >;

  callStatic: {
    WETH9(overrides?: CallOverrides): Promise<string>;

    "checkOracleSlippage(bytes[],uint128[],uint24,uint32)"(
      paths: PromiseOrValue<BytesLike>[],
      amounts: PromiseOrValue<BigNumberish>[],
      maximumTickDivergence: PromiseOrValue<BigNumberish>,
      secondsAgo: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    "checkOracleSlippage(bytes,uint24,uint32)"(
      path: PromiseOrValue<BytesLike>,
      maximumTickDivergence: PromiseOrValue<BigNumberish>,
      secondsAgo: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    factory(overrides?: CallOverrides): Promise<string>;

    registerPool(
      pool: PromiseOrValue<string>,
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      fee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setTime(
      _time: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    testGetBlockStartingAndCurrentTick(
      pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [number, number] & { blockStartingTick: number; currentTick: number }
    >;

    "testGetSyntheticTicks(bytes[],uint128[],uint32)"(
      paths: PromiseOrValue<BytesLike>[],
      amounts: PromiseOrValue<BigNumberish>[],
      secondsAgo: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        averageSyntheticAverageTick: BigNumber;
        averageSyntheticCurrentTick: BigNumber;
      }
    >;

    "testGetSyntheticTicks(bytes,uint32)"(
      path: PromiseOrValue<BytesLike>,
      secondsAgo: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        syntheticAverageTick: BigNumber;
        syntheticCurrentTick: BigNumber;
      }
    >;
  };

  filters: {};

  estimateGas: {
    WETH9(overrides?: CallOverrides): Promise<BigNumber>;

    "checkOracleSlippage(bytes[],uint128[],uint24,uint32)"(
      paths: PromiseOrValue<BytesLike>[],
      amounts: PromiseOrValue<BigNumberish>[],
      maximumTickDivergence: PromiseOrValue<BigNumberish>,
      secondsAgo: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "checkOracleSlippage(bytes,uint24,uint32)"(
      path: PromiseOrValue<BytesLike>,
      maximumTickDivergence: PromiseOrValue<BigNumberish>,
      secondsAgo: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    factory(overrides?: CallOverrides): Promise<BigNumber>;

    registerPool(
      pool: PromiseOrValue<string>,
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setTime(
      _time: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    testGetBlockStartingAndCurrentTick(
      pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "testGetSyntheticTicks(bytes[],uint128[],uint32)"(
      paths: PromiseOrValue<BytesLike>[],
      amounts: PromiseOrValue<BigNumberish>[],
      secondsAgo: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "testGetSyntheticTicks(bytes,uint32)"(
      path: PromiseOrValue<BytesLike>,
      secondsAgo: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    WETH9(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "checkOracleSlippage(bytes[],uint128[],uint24,uint32)"(
      paths: PromiseOrValue<BytesLike>[],
      amounts: PromiseOrValue<BigNumberish>[],
      maximumTickDivergence: PromiseOrValue<BigNumberish>,
      secondsAgo: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "checkOracleSlippage(bytes,uint24,uint32)"(
      path: PromiseOrValue<BytesLike>,
      maximumTickDivergence: PromiseOrValue<BigNumberish>,
      secondsAgo: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registerPool(
      pool: PromiseOrValue<string>,
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setTime(
      _time: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    testGetBlockStartingAndCurrentTick(
      pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "testGetSyntheticTicks(bytes[],uint128[],uint32)"(
      paths: PromiseOrValue<BytesLike>[],
      amounts: PromiseOrValue<BigNumberish>[],
      secondsAgo: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "testGetSyntheticTicks(bytes,uint32)"(
      path: PromiseOrValue<BytesLike>,
      secondsAgo: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
